---
title: "main_code"
author: "Hsiao"
date: "6/7/2021"
output: html_document
---

```{r}
library("tidyverse")
library("openxlsx")
library("data.table")
library("readxl")
library("dplyr")

```


```{r}
#import datasests


d2104<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 225, colNames = FALSE)
# 100 :2010/11/
d2103<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 224, colNames = FALSE)
d2102<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 223, colNames = FALSE)
d2101<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 222, colNames = FALSE)
d2012<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 221, colNames = FALSE)
d2011<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 220, colNames = FALSE)
d2010<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 219, colNames = FALSE)
d2009<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 218, colNames = FALSE)
d2008<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 217, colNames = FALSE)
d2007<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 216, colNames = FALSE)
d2006<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 215, colNames = FALSE)
d2005<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 214, colNames = FALSE)
d2004<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 213, colNames = FALSE)
d2003<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 212, colNames = FALSE)
d2002<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 211, colNames = FALSE)
d2001<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 210, colNames = FALSE)
d1912<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 209, colNames = FALSE)
d1911<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 208, colNames = FALSE)
d1910<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 207, colNames = FALSE)
d1909<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 206, colNames = FALSE)
d1908<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 205, colNames = FALSE)
d1907<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 204, colNames = FALSE)
d1906<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 203, colNames = FALSE)
d1905<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 202, colNames = FALSE)
d1904<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 201, colNames = FALSE)
d1903<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 200, colNames = FALSE)
d1902<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 199, colNames = FALSE)
d1901<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 198, colNames = FALSE)


d1812<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 197, colNames = FALSE)
d1811<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 196, colNames = FALSE)
d1810<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 195, colNames = FALSE)
d1809<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 194, colNames = FALSE)
d1808<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 193, colNames = FALSE)
d1807<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 192, colNames = FALSE)
d1806<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 191, colNames = FALSE)
d1805<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 190, colNames = FALSE)
d1804<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 189, colNames = FALSE)
d1803<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 188, colNames = FALSE)
d1802<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 187, colNames = FALSE)
d1801<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 186, colNames = FALSE)


d1712<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 185, colNames = FALSE)
d1711<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 184, colNames = FALSE)
d1710<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 183, colNames = FALSE)
d1709<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 182, colNames = FALSE)
d1708<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 181, colNames = FALSE)
d1707<- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = 180, colNames = FALSE)




# for (i in 2100:2103){
#paste("d",i, sep = "") <- read.xlsx(xlsxFile="/Users/Ano/Desktop/IO_motorbikes/M04.xlsx", sheet = i-1879, colNames = FALSE)
  
#}  
```


```{r}
# automation 
#d2104 <-as.data.table(d2104)
#d2103 <-as.data.table(d2103)
#d2102 <-as.data.table(d2102)
#d2101 <-as.data.table(d2101)

list2env(eapply(.GlobalEnv, function(x) {if(is.data.frame(x)) {setDT(x)} else {x}}), .GlobalEnv)


top<- function(data){
  return(data[, X4:=toupper(X4)])
} # change into 

data_list <- list(d2104, d2103, d2102, d2101, d2012, d2011 ,d2010, d2009, d2008, d2007, d2006, d2005, d2004,d2003, d2002, d2001, d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901, d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801, d1712, d1711, d1710, d1709, d1708, d1707)

lapply(data_list, top)


inn<- function(x){
  x<-subset(x, X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"))
 return(x)
}

data_list <- list(d2104, d2103, d2102, d2101, d2012, d2011 ,d2010, d2009, d2008, d2007, d2006, d2005, d2004,d2003, d2002, d2001, d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901, d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801)

# lapply(data_list, inn)
# lapply fail
# need to assign I do not know why

d2104<- d2104[ d2104$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2103<- d2103[ d2103$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2102<- d2102[ d2102$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2101<- d2101[ d2101$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]

d2012<- d2012[ d2012$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2011<- d2011[ d2011$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2010<- d2010[ d2010$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2009<- d2009[ d2009$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2008<- d2008[ d2008$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2007<- d2007[ d2007$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2006<- d2006[ d2006$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2005<- d2005[ d2005$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2004<- d2004[ d2004$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2003<- d2003[ d2003$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2002<- d2002[ d2002$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d2001<- d2001[ d2001$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]

d1912<- d1912[ d1912$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1911<- d1911[ d1911$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1910<- d1910[ d1910$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1909<- d1909[ d1909$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1908<- d1908[ d1908$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1907<- d1907[ d1907$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1906<- d1906[ d1906$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1905<- d1905[ d1905$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1904<- d1904[ d1904$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1903<- d1903[ d1903$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1902<- d1902[ d1902$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1901<- d1901[ d1901$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]

d1812<- d1812[ d1812$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1811<- d1811[ d1811$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1810<- d1810[ d1810$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1809<- d1809[ d1809$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1808<- d1808[ d1808$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1807<- d1807[ d1807$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1806<- d1806[ d1806$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1805<- d1805[ d1805$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1804<- d1804[ d1804$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1803<- d1803[ d1803$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1802<- d1802[ d1802$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1801<- d1801[ d1801$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]

d1712<- d1712[ d1712$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1711<- d1711[ d1711$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1710<- d1710[ d1710$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1709<- d1709[ d1709$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1708<- d1708[ d1708$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
d1707<- d1707[ d1707$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]


#list2env(lapply(data_list, function(x) x[, .(col1, col2)]))

# data_list<- lapply(data_list, inn) # take only the ccs
data_list <- list(d2104, d2103, d2102, d2101, d2012, d2011 ,d2010, d2009, d2008, d2007, d2006, d2005, d2004,d2003, d2002, d2001, d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901, d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801, d1712, d1711, d1710, d1709, d1708, d1707)

#set names 

setdtname <- function(data){
  setnames(data,c("X1","X2","X4","X5","X7","X9"),c("firm","type","cc","produce","sales_in","sales_out"))
}
# function works
lapply(data_list, setdtname)

```

---
Meta Programming ||| In progress|||

df.list<-lapply(1:4, function(x) eval(parse(text=paste0("d210", x)))) #In order to store all datasets in one list using their name
names(df.list)<-lapply(1:4, function(x) paste0("d201", x)) #Adding the name of each df in case you want to unlist the list afterwards
for (i in 1:length(df.list)) {
  df.list[[i]][[i$X4]]<-toupper(df.list[[i]][$X4])
}



```{r}
# 2104

#d2104<- d2104[d2104$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
#setnames(d2104, c("X1","X2","X4","X5","X7","X9"),c("firm","type","cc","produce","sales_in","sales_out"))

d2104<- d2104[1:19, firm := "SYM",]
d2104<- d2104[19:34, firm := "SUZUKI",]
d2104<- d2104[35:38, firm := "YAMAHA",]
d2104<- d2104[39:61, firm := "KYMCO",]
d2104<- d2104[71:82, firm := "PGO",]
d2104<- d2104[c(1:61, 71:82),]

d2104$produce<- as.integer(d2104$produce)
d2104$sales_in<- as.integer(d2104$sales_in)
d2104$sales_out<- as.integer(d2104$sales_out)

string<- c("produce","sales_in", "sales_out")
d2104<- d2104[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2104[, "year":=2021, ]
d2104[, "month":=04, ]
# type is drop out here ! 
d2104[, c("year","month","firm","cc","produce","sales_in","sales_out")]
```



```{r}
#2013
# d2103<- d2103[d2103$X4 %in% c("50CC","90CC","100CC","110CC","125CC","150CC","250CC"), ]
# setnames(d2103, c("X1","X2","X4","X5","X7","X9"),c("firm","type","cc","produce","sales_in","sales_out"))

# d2103<- d2103[1:18, firm := "SYM",]
# d2103<- d2103[19:34, firm := "SUZUKI",]
# d2103<- d2103[35:38, firm := "YAMAHA",]
# d2103<- d2103[39:70, firm := "KYMCO",]
# d2103<- d2103[1:70]
# 
# d2103$produce<- as.integer(d2103$produce)
# d2103$sales_in<- as.integer(d2103$sales_in)
# d2103$sales_out<- as.integer(d2103$sales_out)
# 
# string<- c("produce","sales_in", "sales_out")
# d2103<- d2103[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
# d2103[, "year":=2021, ]
# d2103[, "month":=03, ]
# d2103[, c("year","month","firm","cc","produce","sales_in","sales_out")]

```




```{r}
# deal with firm

# d2104<- d2104[1:19, firm := "SYM",]
# d2104<- d2104[19:34, firm := "SUZUKI",]
# d2104<- d2104[35:38, firm := "YAMAHA",]
# d2104<- d2104[39:61, firm := "KYMCO",]
# d2104<- d2104[71:82, firm := "PGO",]
# d2104<- d2104[c(1:61, 71:82),]

d2103<- d2103[1:18, firm := "SYM",]
d2103<- d2103[19:34, firm := "SUZUKI",]
d2103<- d2103[35:38, firm := "YAMAHA",]
d2103<- d2103[39:61, firm := "KYMCO",]
d2103<- d2103[71:82, firm := "PGO",]
d2103<- d2103[c(1:61, 71:82),]

d2102<- d2102[1:18, firm := "SYM",]
d2102<- d2102[19:34, firm := "SUZUKI",]
d2102<- d2102[35:38, firm := "YAMAHA",]
d2102<- d2102[39:61, firm := "KYMCO",]
d2102<- d2102[71:82, firm := "PGO",]
d2102<- d2102[c(1:61, 71:82),]

d2101<- d2101[1:18, firm := "SYM",]
d2101<- d2101[19:34, firm := "SUZUKI",]
d2101<- d2101[35:37, firm := "YAMAHA",]
d2101<- d2101[38:60, firm := "KYMCO",]
d2101<- d2101[70:81, firm := "PGO",]
d2101<- d2101[c(1:61, 70:81),]
```


```{r}
# 
# d2012<- d2012[1:18, firm := "SYM",]
# d2012<- d2012[19:34, firm := "SUZUKI",]
# d2012<- d2012[35:38, firm := "YAMAHA",]
# d2012<- d2012[39:61, firm := "KYMCO",]
# d2012<- d2012[71:82, firm := "PGO",]
# d2012<- d2012[c(1:61, 71:82),]
# 
# d2011<- d2011[1:18, firm := "SYM",]
# d2011<- d2011[19:34, firm := "SUZUKI",]
# d2011<- d2011[35:38, firm := "YAMAHA",]
# d2011<- d2011[39:61, firm := "KYMCO",]
# d2011<- d2011[71:82, firm := "PGO",]
# d2011<- d2011[c(1:61, 71:82),]
# 
# d2010<- d2010[1:18, firm := "SYM",]
# d2010<- d2010[19:34, firm := "SUZUKI",]
# d2010<- d2010[35:38, firm := "YAMAHA",]
# d2010<- d2010[39:61, firm := "KYMCO",]
# d2010<- d2010[71:82, firm := "PGO",]
# d2010<- d2010[c(1:61, 71:82),]

d2009<- d2009[1:19, firm := "SYM",]
d2009<- d2009[20:35, firm := "SUZUKI",]
d2009<- d2009[36:39, firm := "YAMAHA",]
d2009<- d2009[40:62, firm := "KYMCO",]
d2009<- d2009[72:83, firm := "PGO",]
d2009<- d2009[c(1:62, 72:83),]

# d2008<- d2008[1:18, firm := "SYM",]
# d2008<- d2008[19:34, firm := "SUZUKI",]
# d2008<- d2008[35:38, firm := "YAMAHA",]
# d2008<- d2008[39:61, firm := "KYMCO",]
# d2008<- d2008[71:82, firm := "PGO",]
# d2008<- d2008[c(1:61, 71:82),]
# 
# d2007<- d2007[1:18, firm := "SYM",]
# d2007<- d2007[19:34, firm := "SUZUKI",]
# d2007<- d2007[35:38, firm := "YAMAHA",]
# d2007<- d2007[39:61, firm := "KYMCO",]
# d2007<- d2007[71:82, firm := "PGO",]
# d2007<- d2007[c(1:61, 71:82),]
# 
# d2006<- d2006[1:18, firm := "SYM",]
# d2006<- d2006[19:34, firm := "SUZUKI",]
# d2006<- d2006[35:38, firm := "YAMAHA",]
# d2006<- d2006[39:61, firm := "KYMCO",]
# d2006<- d2006[71:82, firm := "PGO",]
# d2006<- d2006[c(1:61, 71:82),]
# 
# d2005<- d2005[1:18, firm := "SYM",]
# d2005<- d2005[19:34, firm := "SUZUKI",]
# d2005<- d2005[35:38, firm := "YAMAHA",]
# d2005<- d2005[39:61, firm := "KYMCO",]
# d2005<- d2005[71:82, firm := "PGO",]
# d2005<- d2005[c(1:61, 71:82),]

test<- list(d2012, d2011, d2010, d2008, d2007,d2006 ,d2005,d2004,d2003,d2002 ,d2001)
# d2009 is strange

lapply(test, function(x) {
   x<- x[1:18, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[19:34, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[35:38, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[39:61, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[71:82, firm :="PGO"]
   return(x)
})

d2012<- d2012[c(1:61, 71:82),]
d2011<- d2011[c(1:61, 71:82),]
d2010<- d2010[c(1:61, 71:82),]
d2008<- d2008[c(1:61, 71:82),]
d2007<- d2007[c(1:61, 71:82),]
d2006<- d2006[c(1:61, 71:82),]
d2005<- d2005[c(1:61, 71:82),]
d2004<- d2004[c(1:61, 71:82),]
d2003<- d2003[c(1:61, 71:82),]
d2002<- d2002[c(1:61, 71:82),]
d2001<- d2001[c(1:61, 71:82),]
```


```{r}
# 2019 year :

test<- list(d1912, d1911)
lapply(test, function(x) {
   x<- x[1:18, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[19:34, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[35:38, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[39:61, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[71:82, firm :="PGO"]
   return(x)
})
# original 109 for 12, 11
# 110 for below

test<- list(d1910, d1909,d1908, d1907, d1906)
lapply(test, function(x) {
   x<- x[1:18, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[19:34, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[35:38, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[39:61, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[71:83, firm :="PGO"]
   return(x)
})
############################
test<- list(d1905, d1904) 
lapply(test, function(x) {
   x<- x[1:18, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[19:36, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[37:40, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[41:63, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[73:85, firm :="PGO"]
   return(x)
})

#############################
test<- list(d1903, d1902, d1901) 
lapply(test, function(x) {
   x<- x[1:19, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[20:37, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[38:41, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[42:64, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[74:86, firm :="PGO"]
   return(x)
})


d1912<- d1912[c(1:61, 71:82),]
d1911<- d1911[c(1:61, 71:82),]
d1910<- d1910[c(1:61, 71:83),]
d1909<- d1909[c(1:61, 71:83),]
d1908<- d1908[c(1:61, 71:83),]
d1907<- d1907[c(1:61, 71:83),]
d1906<- d1906[c(1:61, 71:83),]
d1905<- d1905[c(1:63, 73:85),]
d1904<- d1904[c(1:63, 73:85),]
d1903<- d1903[c(1:64, 74:86),]
d1902<- d1902[c(1:64, 74:86),]
d1901<- d1901[c(1:64, 74:86),]

```



```{r}
# 2018 

test<- list(d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802) 
lapply(test, function(x) {
   x<- x[1:19, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[20:37, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[38:41, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[42:64, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[74:86, firm :="PGO"]
   return(x)
})

d1812<- d1812[c(1:64, 74:86),]
d1811<- d1811[c(1:64, 74:86),]
d1810<- d1810[c(1:64, 74:86),]
d1809<- d1809[c(1:64, 74:86),]
d1808<- d1808[c(1:64, 74:86),]
d1807<- d1807[c(1:64, 74:86),]
d1806<- d1806[c(1:64, 74:86),]
d1805<- d1805[c(1:64, 74:86),]
d1804<- d1804[c(1:64, 74:86),]
d1803<- d1803[c(1:64, 74:86),]
d1802<- d1802[c(1:64, 74:86),]



d1801<- d1801[1:19, firm := "SYM",]
d1801<- d1801[20:36, firm := "SUZUKI",]
d1801<- d1801[37:40, firm := "YAMAHA",]
d1801<- d1801[41:63, firm := "KYMCO",]
d1801<- d1801[73:86, firm := "PGO",]
d1801<- d1801[c(1:63, 73:86),]

```


```{r}
# 2017

test<- list(d1712, d1711, d1710, d1709, d1708, d1707) 
lapply(test, function(x) {
   x<- x[1:19, firm :="SYM"]
   return(x)
})

lapply(test, function(x) {
   x<- x[20:37, firm :="SUZUKI"]
   return(x)
})

lapply(test, function(x) {
   x<- x[38:41, firm :="YAMAHA"]
   return(x)
})

lapply(test, function(x) {
   x<- x[42:64, firm :="KYMCO"]
   return(x)
})

lapply(test, function(x) {
   x<- x[74:86, firm :="PGO"]
   return(x)
})

d1712<- d1712[c(1:64, 74:86),]
d1711<- d1711[c(1:64, 74:86),]
d1710<- d1710[c(1:64, 74:86),]
d1709<- d1709[c(1:64, 74:86),]
d1708<- d1708[c(1:64, 74:86),]
d1707<- d1707[c(1:64, 74:86),]


```



```{r}
# 

data_list <- list(d2104, d2103, d2102, d2101, d2012, d2011 ,d2010, d2009, d2008, d2007, d2006, d2005, d2004,d2003, d2002, d2001, d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901, d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801, d1712, d1711, d1710, d1709, d1708, d1707)

dinteg<- function(data){
  return(data[, produce:=as.integer(produce)])
} # change into 
lapply(data_list, dinteg)
class(d1803$produce)
lapply(data_list, function(x) { return(x[, sales_in := as.integer(sales_in)])})
lapply(data_list, function(x) { return(x[, sales_out := as.integer(sales_out)])})

string<- c("produce","sales_in", "sales_out")

d2103<- d2103[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2102<- d2102[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2101<- d2101[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]

d2012<- d2012[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2011<- d2011[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2010<- d2010[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2009<- d2009[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2008<- d2008[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2007<- d2007[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2006<- d2006[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2005<- d2005[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2004<- d2004[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2003<- d2003[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2002<- d2002[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d2001<- d2001[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]

d1912<- d1912[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1911<- d1911[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1910<- d1910[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1909<- d1909[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1908<- d1908[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1907<- d1907[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1906<- d1906[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1905<- d1905[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1904<- d1904[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1903<- d1903[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1902<- d1902[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1901<- d1901[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]

d1812<- d1812[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1811<- d1811[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1810<- d1810[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1809<- d1809[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1808<- d1808[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1807<- d1807[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1806<- d1806[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1805<- d1805[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1804<- d1804[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1803<- d1803[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1802<- d1802[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1801<- d1801[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]

d1712<- d1712[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1711<- d1711[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1710<- d1710[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1709<- d1709[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1708<- d1708[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]
d1707<- d1707[ , lapply(.SD, sum), by = .(cc, firm), .SDcols = string]

data_list <- list(d2104, d2103, d2102, d2101, d2012, d2011 ,d2010, d2009, d2008, d2007, d2006, d2005, d2004,d2003, d2002, d2001, d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901, d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801,d1712, d1711, d1710, d1709, d1708, d1707)

lapply(list(d2103, d2102, d2101), function(x){ return(x[ ,"year":=2021,])})
lapply(list(d2012, d2011, d2010, d2009, d2008, d2007, d2006, d2005, d2004, d2003, d2002, d2001), function(x){ return(x[,"year":=2020])})
lapply(list(d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901), function(x){ return(x[,"year":=2019])})
lapply(list(d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801), function(x){ return(x[,"year":=2018])})
lapply(list(d1712, d1711, d1710, d1709, d1708, d1707), function(x){ return(x[,"year":=2017])})

lapply(list(d2101, d2001, d1901, d1801),function(x){ return(x[,"month":=1])})
lapply(list(d2102, d2002, d1902, d1802),function(x){ return(x[,"month":=2])})
lapply(list(d2103, d2003, d1903, d1803),function(x){ return(x[,"month":=3])})
lapply(list( d2004, d1904, d1804),function(x){ return(x[,"month":=4])})
lapply(list( d2005, d1904, d1805),function(x){ return(x[,"month":=5])})
lapply(list( d2006, d1906, d1806),function(x){ return(x[,"month":=6])})
lapply(list( d2007, d1907, d1807, d1707),function(x){ return(x[,"month":=7])})
lapply(list( d2008, d1908, d1808, d1708),function(x){ return(x[,"month":=8])})
lapply(list( d2009, d1909, d1809, d1709),function(x){ return(x[,"month":=9])})
lapply(list( d2010, d1910, d1810, d1710),function(x){ return(x[,"month":=10])})
lapply(list( d2011, d1911, d1811, d1711),function(x){ return(x[,"month":=11])})
lapply(list( d2012, d1912, d1812, d1712),function(x){ return(x[,"month":=12])})
```

```{r}

data_list <- list(d2104, d2103, d2102, d2101, d2012, d2011 ,d2010, d2009, d2008, d2007, d2006, d2005, d2004,d2003, d2002, d2001, d1912, d1911, d1910, d1909, d1908, d1907, d1906, d1905, d1904, d1903, d1902, d1901, d1812, d1811, d1810, d1809, d1808, d1807, d1806, d1805, d1804, d1803, d1802, d1801, d1712, d1711, d1710, d1709, d1708, d1707)
data<- rbind(unlist(data_list))

data<- bind_rows(data_list)
write.table(data, file = "sales_data.csv", sep = ",",col.names = TRUE, row.names = FALSE)
#extrating the data 
# drop out 
# 什麼時候做好了？？？？
# d2102[, c("year","month","firm","cc","produce","sales_in","sales_out")]

```


